name: end-to-end test

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./Front
          browser: chrome
          headless: true
          build: npx cypress info