name: E2ETests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./Front
          browser: chrome
          headless: true
          start: npm start
          wait-on: 'http://localhost:3000/'
          config: baseUrl=http://localhost:3000/